apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nodejstest
  description: Node.js golden-path service with Jenkins, Helm, and Sonar
  tags:
    - nodejs
    - golden-path
    - jenkins
    - helm
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rmallam/nodejstest
    jenkins.io/job-full-name: demo/nodejstest
    sonarqube.org/project-key: nodejstest
    argocd/app-name: nodejstest
    argocd/app-namespace: openshift-gitops
    backstage.io/kubernetes-id: nodejstest
    backstage.io/kubernetes-namespace: demo-dev
    kiali.io/namespace: demo-dev
    vault.io/secrets-path: rhdh
    jira/project-key: SCRUM
    jira/component: nodejstest
    snyk.io/org-id: stub-org
    snyk.io/org-name: stub-org
    snyk.io/project-ids: stub
    servicenow.com/entity-id: demo
    jfrog-artifactory/image-name: nodejstest
    dynatrace.com/dynatrace-entity-id: SERVICE-39720C1E0047A5C0
    acme.io/devfile-path: devfile.yaml
    acme.io/helm-chart: chart
    acme.io/mesh: ambient
    acme.io/devspaces-url: https://devspaces.apps.rosa.rosa-89s85.bhg0.p3.openshiftapps.com
    acme.io/devspaces-factory-url: https://devspaces.apps.rosa.rosa-89s85.bhg0.p3.openshiftapps.com#https://github.com/rmallam/nodejstest?new&devfilePath=devfile.yaml
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
